name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Install opencv
      run: pip install opencv-python
      
    - name: Install gtts
      run: pip install gtts
    
    - name: Install playsound
      run: pip install playsound

    - name: Build EXE
      run: pyinstaller --onefile photo_spyer.py --hidden-import=gtts -hidden-import=playsound

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: exe-file
        path: dist/*.exe